"""empty message

Revision ID: 1637d76700ba
Revises: a125e6ac95d6
Create Date: 2026-01-31 14:52:51.127319

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1637d76700ba"
down_revision: Union[str, None] = "a125e6ac95d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "http_request_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("path", sa.String(length=500), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("user_agent", sa.String(length=500), nullable=False),
        sa.Column("referer", sa.String(length=500), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("content_length", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_http_request_logs")),
    )
    op.create_index(
        op.f("ix_http_request_logs_created_at"),
        "http_request_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_http_request_logs_ip_address"),
        "http_request_logs",
        ["ip_address"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_http_request_logs_ip_address"), table_name="http_request_logs"
    )
    op.drop_index(
        op.f("ix_http_request_logs_created_at"), table_name="http_request_logs"
    )
    op.drop_table("http_request_logs")
    # ### end Alembic commands ###
