"""empty message

Revision ID: e265bfe32c8c
Revises: fc447514f941
Create Date: 2026-03-20 10:46:04.138450

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e265bfe32c8c"
down_revision: Union[str, None] = "fc447514f941"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "news_items",
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column(
            "sources",
            postgresql.ARRAY(sa.String(), dimensions=1),
            nullable=True,
        ),
        sa.Column(
            "article_urls",
            postgresql.ARRAY(sa.String(length=2048), dimensions=1),
            nullable=True,
        ),
        sa.Column(
            "bookmarked", sa.Boolean(), server_default="f", nullable=False
        ),
        sa.Column("reaction", sa.String(length=10), nullable=True),
        sa.Column("description", sa.String(length=5000), nullable=False),
        sa.Column(
            "detailed_description", sa.String(length=5000), nullable=True
        ),
        sa.Column(
            "extended_description", sa.String(length=5000), nullable=True
        ),
        sa.Column("human_feedback", sa.String(length=5000), nullable=True),
        sa.Column(
            "needs_ai_analysis",
            sa.Boolean(),
            server_default="f",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_news_items")),
    )
    op.create_index(
        op.f("ix_news_items_created_at"),
        "news_items",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_news_items_needs_ai_analysis"),
        "news_items",
        ["needs_ai_analysis"],
        unique=False,
    )
    op.create_index(
        op.f("ix_news_items_reaction"),
        "news_items",
        ["reaction"],
        unique=False,
    )
    op.create_table(
        "analytics_ai",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pipeline_name", sa.String(length=255), nullable=False),
        sa.Column("trace_id", sa.String(length=12), nullable=False),
        sa.Column(
            "agent_stats",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("total_calls", sa.Integer(), nullable=False),
        sa.Column("total_errors", sa.Integer(), nullable=False),
        sa.Column("wall_time_s", sa.Float(), nullable=False),
        sa.Column("estimated_cost", sa.Float(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_analytics_ai_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analytics_ai")),
    )
    op.create_index(
        op.f("ix_analytics_ai_created_at"),
        "analytics_ai",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "jobs",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("job_type", sa.String(length=100), nullable=False),
        sa.Column(
            "_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("interval_minutes", sa.Integer(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default="t", nullable=False
        ),
        sa.Column("last_run_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "next_run_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_status", sa.String(length=20), nullable=True),
        sa.Column("last_error", sa.String(length=1000), nullable=True),
        sa.Column(
            "run_count", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_jobs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.add_column(
        "exchange_rates",
        sa.Column(
            "source", sa.String(length=20), server_default="nbu", nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column("news_filter_prompt", sa.String(length=5000), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "news_preference_profile", sa.String(length=10000), nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "gc_retention_days",
            sa.Integer(),
            server_default="3",
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "analyze_preferences",
            sa.Boolean(),
            server_default="t",
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "timezone",
            sa.String(length=50),
            server_default="UTC",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "timezone")
    op.drop_column("users", "analyze_preferences")
    op.drop_column("users", "gc_retention_days")
    op.drop_column("users", "news_preference_profile")
    op.drop_column("users", "news_filter_prompt")
    op.drop_column("exchange_rates", "source")
    op.drop_table("jobs")
    op.drop_index(
        op.f("ix_analytics_ai_created_at"), table_name="analytics_ai"
    )
    op.drop_table("analytics_ai")
    op.drop_index(op.f("ix_news_items_reaction"), table_name="news_items")
    op.drop_index(
        op.f("ix_news_items_needs_ai_analysis"), table_name="news_items"
    )
    op.drop_index(op.f("ix_news_items_created_at"), table_name="news_items")
    op.drop_table("news_items")
    # ### end Alembic commands ###
