"""empty message

Revision ID: fc447514f941
Revises: 2a3b4c5d6e7f
Create Date: 2026-02-05 22:53:21.820620

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc447514f941"
down_revision: Union[str, None] = "2a3b4c5d6e7f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exchange_rates",
        sa.Column("cc_from", sa.String(length=3), nullable=False),
    )
    op.add_column(
        "exchange_rates",
        sa.Column("cc_to", sa.String(length=3), nullable=False),
    )
    op.add_column(
        "exchange_rates", sa.Column("date", sa.DATE(), nullable=False)
    )
    op.drop_constraint(
        op.f("uq_exchange_rates_code_date"), "exchange_rates", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_exchange_rates_cc_from"),
        "exchange_rates",
        ["cc_from", "cc_to", "date"],
    )
    op.drop_column("exchange_rates", "currency_code")
    op.drop_column("exchange_rates", "exchange_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exchange_rates",
        sa.Column(
            "exchange_date", sa.DATE(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "exchange_rates",
        sa.Column(
            "currency_code",
            sa.VARCHAR(length=3),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        op.f("uq_exchange_rates_cc_from"), "exchange_rates", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_exchange_rates_code_date"),
        "exchange_rates",
        ["currency_code", "exchange_date"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("exchange_rates", "date")
    op.drop_column("exchange_rates", "cc_to")
    op.drop_column("exchange_rates", "cc_from")
    # ### end Alembic commands ###
